name: Build with bob

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 2 2 */4 *'
  workflow_dispatch:
env:
  BUILD_SERVER: 'https://build.defold.com'

jobs:
  build_with_bob:
    strategy:
      matrix:
        platform: [armv7-android, x86_64-linux, x86_64-win32, x86-win32, js-web]
    runs-on: ubuntu-latest

    name: Build
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
      - uses: dapetcu21/setup-defold@v3.0.3
      - run: java -jar $BOB --platform=${{ matrix.platform }} build --build-server=${{env.BUILD_SERVER}}
